### ISSUE TITLE
[5.10.1] BlockCraftery - Rendering Issue

### ISSUE THREAD

**Issue by Elvarion** [AllTheMods/ATM-3#790]
## Expected Behavior

They should render normally. They did this in 5.9.8d
https://gyazo.com/71949fb193c3d394493e249baf2c733e

## Current Behavior

BlockCraftery Slanted blocks Render Black on the Top and also Sides.
Only happens in certain rotations.
https://gyazo.com/10fca074aaf746f75a8b3f091dfd36aa

## Steps to Reproduce

1. Place Slant while looking towards a block like this
https://gyazo.com/f8f3a4f479f69c975c0663aaf02989e7
2. Look ontop of the Slanted Block

**Comment by Yoosk** [comment]
Should be fixed in current version of pack, can you test? (beta 5.11.0)

**Comment by Elvarion** [comment]
Will try and reply back in a couple of hours. Currently very busy atm sorry

**Comment by Galeban** [comment]
Playing on a Continuum server and can confirm that the rendering issue is still present with the slanted blocks when placed upside down.

**Comment by FallenEagle1** [comment]
What version of the mod is it that is in that pack?

**Comment by Elvarion** [comment]
blockcraftery-0.1.3

**Comment by FallenEagle1** [comment]
It looks like part of the update to mod version of blockcraftery 1.0.0 is supposed to fix this.
