### ISSUE TITLE
MineColonies<->Storage drawers  crash

### ISSUE THREAD

**Issue by Retovath** [AllTheMods/ATM-3#845]
Crafting recipe check for storage drawers crashes local client

## Expected Behavior

Client shouldn't crash when an item is inserted into an unused compacting drawer by a player.

## Current Behavior

Client crashes when right clicking to insert an item into a new compacting drawer. 

## Possible Solution

Update pack when this commit becomes available: https://github.com/ldtteam/minecolonies/issues/3443

## Steps to Reproduce

1. Place new compacting drawer
2. Put virtually any item in it-> Tested with fluxed electrum, fluxed electrum blocks, and ultimate universal cables.
3. Client crash.
4.

## Log

https://gist.github.com/Retovath/0bb25a074d2405af774d69d8a7f9203a

## Detailed Description

Suggestion: please update minecolonies at the next available opportunity!

**Comment by Yamza** [comment]
There are a couple potential options. 

First one would be to update Minecolonies and tell everyone that joins the server to update as well. Not the greatest of ideas, since that means everyone needing to do something and could run into new bugs.

Second option is to downgrade back to 5.11.2, then remove the storage drawers the villagers are trying to access, then update again.

Or wait for a pack update, but I'm not sure when that could be.

**Comment by NEXUS2345** [comment]
This issue would have been fixed if Storage Drawers and Minecolonies were updated, but as of 5.12.1 they still haven't been updated.

**Comment by FallenEagle1** [comment]
We were also told by the dev not to update until a specific release comes out

**Comment by Dviper18** [comment]
Issue still persists. https://gist.github.com/Dviper18/1d6506c6df3a3468cacc52d9461c9992
